<?php

namespace Database\Seeders;

use App\Models\Food;
use Illuminate\Database\Seeder;

class FoodSeeder extends Seeder
{
    public function run(): void
    {
        $foods = [
            // Grains & Cereals
            ['name' => 'Oats',           'category' => 'Grains',    'calories' => 389, 'protein' => 17,  'carbs' => 66, 'fat' => 7,  'fiber' => 10.6, 'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 55, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Brown Rice',     'category' => 'Grains',    'calories' => 216, 'protein' => 5,   'carbs' => 45, 'fat' => 1.8,'fiber' => 3.5,  'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 50, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'White Rice',     'category' => 'Grains',    'calories' => 130, 'protein' => 2.7, 'carbs' => 28, 'fat' => 0.3,'fiber' => 0.4,  'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 73, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => false],
            ['name' => 'Whole Wheat Bread','category' => 'Grains',  'calories' => 247, 'protein' => 13,  'carbs' => 41, 'fat' => 4,  'fiber' => 7,    'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => false, 'glycemic_index' => 51, 'allergens' => ['gluten'], 'is_low_sodium' => false, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Quinoa',         'category' => 'Grains',    'calories' => 120, 'protein' => 4.4, 'carbs' => 21, 'fat' => 2,  'fiber' => 2.8,  'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 53, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Roti (Chapati)', 'category' => 'Grains',    'calories' => 297, 'protein' => 9.4, 'carbs' => 55, 'fat' => 4.6,'fiber' => 3.9,  'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 62, 'allergens' => ['gluten'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => false],

            // Proteins - Vegetarian
            ['name' => 'Paneer',         'category' => 'Dairy',     'calories' => 265, 'protein' => 18,  'carbs' => 3,  'fat' => 21, 'fiber' => 0,    'serving_size' => 100, 'is_veg' => true,  'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 27, 'allergens' => ['dairy'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => false, 'is_pcod_friendly' => false],
            ['name' => 'Tofu',           'category' => 'Legumes',   'calories' => 76,  'protein' => 8,   'carbs' => 2,  'fat' => 4.8,'fiber' => 0.3,  'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 15, 'allergens' => ['soy'], 'is_low_sodium' => true, 'is_thyroid_friendly' => false, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Lentils (Dal)',   'category' => 'Legumes',   'calories' => 116, 'protein' => 9,   'carbs' => 20, 'fat' => 0.4,'fiber' => 7.9,  'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 32, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Chickpeas',      'category' => 'Legumes',   'calories' => 164, 'protein' => 8.9, 'carbs' => 27, 'fat' => 2.6,'fiber' => 7.6,  'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => false, 'glycemic_index' => 28, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Greek Yogurt',   'category' => 'Dairy',     'calories' => 97,  'protein' => 9,   'carbs' => 6,  'fat' => 5,  'fiber' => 0,    'serving_size' => 100, 'is_veg' => true,  'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 11, 'allergens' => ['dairy'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => false],
            ['name' => 'Milk (Full Fat)','category' => 'Dairy',     'calories' => 61,  'protein' => 3.2, 'carbs' => 4.8,'fat' => 3.3,'fiber' => 0,    'serving_size' => 100, 'is_veg' => true,  'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 27, 'allergens' => ['dairy'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => false, 'is_pcod_friendly' => false],
            ['name' => 'Rajma (Kidney Beans)','category' => 'Legumes','calories' => 127,'protein' => 8.7,'carbs' => 22.8,'fat' => 0.5,'fiber' => 6.4, 'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => false, 'glycemic_index' => 24, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],

            // Proteins - Non-Vegetarian
            ['name' => 'Chicken Breast', 'category' => 'Poultry',   'calories' => 165, 'protein' => 31,  'carbs' => 0,  'fat' => 3.6,'fiber' => 0,    'serving_size' => 100, 'is_veg' => false, 'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 0, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Eggs',           'category' => 'Poultry',   'calories' => 155, 'protein' => 13,  'carbs' => 1.1,'fat' => 11, 'fiber' => 0,    'serving_size' => 100, 'is_veg' => false, 'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 0, 'allergens' => ['eggs'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Salmon',         'category' => 'Seafood',   'calories' => 208, 'protein' => 20,  'carbs' => 0,  'fat' => 13, 'fiber' => 0,    'serving_size' => 100, 'is_veg' => false, 'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 0, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Tuna',           'category' => 'Seafood',   'calories' => 144, 'protein' => 23,  'carbs' => 0,  'fat' => 5,  'fiber' => 0,    'serving_size' => 100, 'is_veg' => false, 'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 0, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Mutton (Lamb)',  'category' => 'Meat',      'calories' => 294, 'protein' => 25,  'carbs' => 0,  'fat' => 21, 'fiber' => 0,    'serving_size' => 100, 'is_veg' => false, 'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 0, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => false, 'is_pcod_friendly' => true],

            // Fruits
            ['name' => 'Banana',         'category' => 'Fruits',    'calories' => 89,  'protein' => 1.1, 'carbs' => 23, 'fat' => 0.3,'fiber' => 2.6,  'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 51, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Apple',          'category' => 'Fruits',    'calories' => 52,  'protein' => 0.3, 'carbs' => 14, 'fat' => 0.2,'fiber' => 2.4,  'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 36, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Mango',          'category' => 'Fruits',    'calories' => 60,  'protein' => 0.8, 'carbs' => 15, 'fat' => 0.4,'fiber' => 1.6,  'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 51, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Papaya',         'category' => 'Fruits',    'calories' => 43,  'protein' => 0.5, 'carbs' => 11, 'fat' => 0.3,'fiber' => 1.7,  'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 60, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => false],
            ['name' => 'Orange',         'category' => 'Fruits',    'calories' => 47,  'protein' => 0.9, 'carbs' => 12, 'fat' => 0.1,'fiber' => 2.4,  'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 45, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Watermelon',     'category' => 'Fruits',    'calories' => 30,  'protein' => 0.6, 'carbs' => 7.6,'fat' => 0.2,'fiber' => 0.4,  'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 72, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => false],
            ['name' => 'Strawberry',     'category' => 'Fruits',    'calories' => 32,  'protein' => 0.7, 'carbs' => 7.7,'fat' => 0.3,'fiber' => 2,    'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 41, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],

            // Vegetables
            ['name' => 'Spinach',        'category' => 'Vegetables','calories' => 23,  'protein' => 2.9, 'carbs' => 3.6,'fat' => 0.4,'fiber' => 2.2,  'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => false, 'glycemic_index' => 15, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Broccoli',       'category' => 'Vegetables','calories' => 34,  'protein' => 2.8, 'carbs' => 7,  'fat' => 0.4,'fiber' => 2.6,  'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 15, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => false, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Carrot',         'category' => 'Vegetables','calories' => 41,  'protein' => 0.9, 'carbs' => 10, 'fat' => 0.2,'fiber' => 2.8,  'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 39, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Tomato',         'category' => 'Vegetables','calories' => 18,  'protein' => 0.9, 'carbs' => 3.9,'fat' => 0.2,'fiber' => 1.2,  'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => false, 'glycemic_index' => 15, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Cucumber',       'category' => 'Vegetables','calories' => 15,  'protein' => 0.7, 'carbs' => 3.6,'fat' => 0.1,'fiber' => 0.5,  'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 15, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Sweet Potato',   'category' => 'Vegetables','calories' => 86,  'protein' => 1.6, 'carbs' => 20, 'fat' => 0.1,'fiber' => 3,    'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 63, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => false],
            ['name' => 'Mushroom',       'category' => 'Vegetables','calories' => 22,  'protein' => 3.1, 'carbs' => 3.3,'fat' => 0.3,'fiber' => 1,    'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => false, 'glycemic_index' => 10, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],

            // Nuts & Seeds
            ['name' => 'Almonds',        'category' => 'Nuts',      'calories' => 579, 'protein' => 21,  'carbs' => 22, 'fat' => 50, 'fiber' => 12.5, 'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 0, 'allergens' => ['nuts'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Walnuts',        'category' => 'Nuts',      'calories' => 654, 'protein' => 15,  'carbs' => 14, 'fat' => 65, 'fiber' => 6.7,  'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 15, 'allergens' => ['nuts'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Chia Seeds',     'category' => 'Seeds',     'calories' => 486, 'protein' => 17,  'carbs' => 42, 'fat' => 31, 'fiber' => 34.4, 'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 1, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Flax Seeds',     'category' => 'Seeds',     'calories' => 534, 'protein' => 18,  'carbs' => 29, 'fat' => 42, 'fiber' => 27.3, 'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 35, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Peanuts',        'category' => 'Nuts',      'calories' => 567, 'protein' => 26,  'carbs' => 16, 'fat' => 49, 'fiber' => 8.5,  'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 14, 'allergens' => ['nuts'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Makhana (Fox Nut)','category' => 'Snacks',  'calories' => 347, 'protein' => 9.7, 'carbs' => 77, 'fat' => 0.1,'fiber' => 14.5, 'serving_size' => 100, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 55, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],

            // Oils & Fats
            ['name' => 'Olive Oil',      'category' => 'Oils',      'calories' => 884, 'protein' => 0,   'carbs' => 0,  'fat' => 100,'fiber' => 0,    'serving_size' => 15,  'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 0, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Ghee',           'category' => 'Dairy',     'calories' => 900, 'protein' => 0,   'carbs' => 0,  'fat' => 100,'fiber' => 0,    'serving_size' => 15,  'is_veg' => true,  'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 0, 'allergens' => ['dairy'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => false, 'is_pcod_friendly' => false],

            // Beverages
            ['name' => 'Green Tea',      'category' => 'Beverages', 'calories' => 1,   'protein' => 0,   'carbs' => 0,  'fat' => 0,  'fiber' => 0,    'serving_size' => 240, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 0, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Coconut Water',  'category' => 'Beverages', 'calories' => 19,  'protein' => 0.7, 'carbs' => 3.7,'fat' => 0.2,'fiber' => 1.1,  'serving_size' => 240, 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 54, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],

            // Additional Grains
            ['name' => 'Barley', 'category' => 'Grains', 'calories' => 354, 'protein' => 12.5, 'carbs' => 73.5, 'fat' => 2.3, 'fiber' => 17.3, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 28, 'allergens' => ['gluten'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Millet', 'category' => 'Grains', 'calories' => 378, 'protein' => 11, 'carbs' => 73, 'fat' => 4.2, 'fiber' => 8.5, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 71, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => false],
            ['name' => 'Buckwheat', 'category' => 'Grains', 'calories' => 343, 'protein' => 13.3, 'carbs' => 71.5, 'fat' => 3.4, 'fiber' => 10, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 45, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Whole Wheat Pasta', 'category' => 'Grains', 'calories' => 348, 'protein' => 14.5, 'carbs' => 75, 'fat' => 1.5, 'fiber' => 9.2, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => false, 'glycemic_index' => 37, 'allergens' => ['gluten'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Cornmeal', 'category' => 'Grains', 'calories' => 362, 'protein' => 8.1, 'carbs' => 76.9, 'fat' => 3.6, 'fiber' => 7.3, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 68, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => false],
            
            // Additional Legumes & Plant Proteins
            ['name' => 'Soybeans', 'category' => 'Legumes', 'calories' => 446, 'protein' => 36.5, 'carbs' => 30.2, 'fat' => 19.9, 'fiber' => 9.3, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 18, 'allergens' => ['soy'], 'is_low_sodium' => true, 'is_thyroid_friendly' => false, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Edamame', 'category' => 'Legumes', 'calories' => 121, 'protein' => 11.9, 'carbs' => 8.9, 'fat' => 5.2, 'fiber' => 5.2, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 20, 'allergens' => ['soy'], 'is_low_sodium' => true, 'is_thyroid_friendly' => false, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Mung Beans', 'category' => 'Legumes', 'calories' => 347, 'protein' => 23.9, 'carbs' => 62.6, 'fat' => 1.2, 'fiber' => 16.3, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 31, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Black Beans', 'category' => 'Legumes', 'calories' => 341, 'protein' => 21.6, 'carbs' => 62.4, 'fat' => 1.4, 'fiber' => 15.5, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => false, 'glycemic_index' => 30, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Tempeh', 'category' => 'Legumes', 'calories' => 192, 'protein' => 20.3, 'carbs' => 7.6, 'fat' => 10.8, 'fiber' => 0, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 15, 'allergens' => ['soy'], 'is_low_sodium' => true, 'is_thyroid_friendly' => false, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Seitan', 'category' => 'Legumes', 'calories' => 370, 'protein' => 75.2, 'carbs' => 13.7, 'fat' => 1.9, 'fiber' => 0.6, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 15, 'allergens' => ['gluten'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            
            // Additional Dairy
            ['name' => 'Cottage Cheese', 'category' => 'Dairy', 'calories' => 98, 'protein' => 11.1, 'carbs' => 3.4, 'fat' => 4.3, 'fiber' => 0, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 10, 'allergens' => ['dairy'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => false],
            ['name' => 'Cheddar Cheese', 'category' => 'Dairy', 'calories' => 402, 'protein' => 25, 'carbs' => 1.3, 'fat' => 33.1, 'fiber' => 0, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 0, 'allergens' => ['dairy'], 'is_low_sodium' => false, 'is_thyroid_friendly' => true, 'is_heart_friendly' => false, 'is_pcod_friendly' => false],
            ['name' => 'Mozzarella', 'category' => 'Dairy', 'calories' => 280, 'protein' => 28, 'carbs' => 3.1, 'fat' => 17.1, 'fiber' => 0, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 0, 'allergens' => ['dairy'], 'is_low_sodium' => false, 'is_thyroid_friendly' => true, 'is_heart_friendly' => false, 'is_pcod_friendly' => false],
            
            // Additional Non-Veg
            ['name' => 'Turkey Breast', 'category' => 'Poultry', 'calories' => 189, 'protein' => 29, 'carbs' => 0.1, 'fat' => 7.4, 'fiber' => 0, 'serving_size' => 100, 'is_veg' => false, 'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 0, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Beef Steak', 'category' => 'Meat', 'calories' => 271, 'protein' => 25, 'carbs' => 0, 'fat' => 19, 'fiber' => 0, 'serving_size' => 100, 'is_veg' => false, 'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 0, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => false, 'is_pcod_friendly' => true],
            ['name' => 'Pork Chops', 'category' => 'Meat', 'calories' => 231, 'protein' => 24, 'carbs' => 0, 'fat' => 14, 'fiber' => 0, 'serving_size' => 100, 'is_veg' => false, 'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 0, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => false, 'is_pcod_friendly' => true],
            ['name' => 'Shrimp', 'category' => 'Seafood', 'calories' => 99, 'protein' => 24, 'carbs' => 0.2, 'fat' => 0.3, 'fiber' => 0, 'serving_size' => 100, 'is_veg' => false, 'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 0, 'allergens' => ['shellfish'], 'is_low_sodium' => false, 'is_thyroid_friendly' => true, 'is_heart_friendly' => false, 'is_pcod_friendly' => true],
            ['name' => 'Sardines', 'category' => 'Seafood', 'calories' => 208, 'protein' => 24.6, 'carbs' => 0, 'fat' => 11.5, 'fiber' => 0, 'serving_size' => 100, 'is_veg' => false, 'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 0, 'allergens' => ['shellfish'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Cod', 'category' => 'Seafood', 'calories' => 82, 'protein' => 17.8, 'carbs' => 0, 'fat' => 0.7, 'fiber' => 0, 'serving_size' => 100, 'is_veg' => false, 'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 0, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Duck Meat', 'category' => 'Poultry', 'calories' => 337, 'protein' => 19, 'carbs' => 0, 'fat' => 28, 'fiber' => 0, 'serving_size' => 100, 'is_veg' => false, 'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 0, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => false, 'is_pcod_friendly' => true],
            
            // Additional Fruits
            ['name' => 'Pineapple', 'category' => 'Fruits', 'calories' => 50, 'protein' => 0.5, 'carbs' => 13.1, 'fat' => 0.1, 'fiber' => 1.4, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 59, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => false],
            ['name' => 'Grapefruit', 'category' => 'Fruits', 'calories' => 42, 'protein' => 0.8, 'carbs' => 10.7, 'fat' => 0.1, 'fiber' => 1.6, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 25, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Blueberries', 'category' => 'Fruits', 'calories' => 57, 'protein' => 0.7, 'carbs' => 14.5, 'fat' => 0.3, 'fiber' => 2.4, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 53, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Raspberries', 'category' => 'Fruits', 'calories' => 52, 'protein' => 1.2, 'carbs' => 11.9, 'fat' => 0.7, 'fiber' => 6.5, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 32, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Kiwi', 'category' => 'Fruits', 'calories' => 61, 'protein' => 1.1, 'carbs' => 14.7, 'fat' => 0.5, 'fiber' => 3, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 50, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Peach', 'category' => 'Fruits', 'calories' => 39, 'protein' => 0.9, 'carbs' => 9.5, 'fat' => 0.3, 'fiber' => 1.5, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 42, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Plum', 'category' => 'Fruits', 'calories' => 46, 'protein' => 0.7, 'carbs' => 11.4, 'fat' => 0.3, 'fiber' => 1.4, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 40, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Pear', 'category' => 'Fruits', 'calories' => 57, 'protein' => 0.4, 'carbs' => 15.2, 'fat' => 0.1, 'fiber' => 3.1, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 38, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Grapes', 'category' => 'Fruits', 'calories' => 69, 'protein' => 0.7, 'carbs' => 18.1, 'fat' => 0.2, 'fiber' => 0.9, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 59, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => false],
            ['name' => 'Cherries', 'category' => 'Fruits', 'calories' => 50, 'protein' => 1, 'carbs' => 12, 'fat' => 0.3, 'fiber' => 1.6, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 22, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            
            // Additional Vegetables
            ['name' => 'Cabbage', 'category' => 'Vegetables', 'calories' => 25, 'protein' => 1.3, 'carbs' => 5.8, 'fat' => 0.1, 'fiber' => 2.5, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 10, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => false, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Cauliflower', 'category' => 'Vegetables', 'calories' => 25, 'protein' => 1.9, 'carbs' => 5, 'fat' => 0.3, 'fiber' => 2, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 15, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => false, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Bell Pepper', 'category' => 'Vegetables', 'calories' => 20, 'protein' => 0.9, 'carbs' => 4.6, 'fat' => 0.2, 'fiber' => 1.7, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 15, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Eggplant', 'category' => 'Vegetables', 'calories' => 25, 'protein' => 1, 'carbs' => 6, 'fat' => 0.2, 'fiber' => 3, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 15, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Zucchini', 'category' => 'Vegetables', 'calories' => 17, 'protein' => 1.2, 'carbs' => 3.1, 'fat' => 0.3, 'fiber' => 1, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 15, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Green Beans', 'category' => 'Vegetables', 'calories' => 31, 'protein' => 1.8, 'carbs' => 7, 'fat' => 0.2, 'fiber' => 2.7, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 32, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Peas', 'category' => 'Vegetables', 'calories' => 81, 'protein' => 5.4, 'carbs' => 14.5, 'fat' => 0.4, 'fiber' => 5.1, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 48, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Asparagus', 'category' => 'Vegetables', 'calories' => 20, 'protein' => 2.2, 'carbs' => 3.9, 'fat' => 0.1, 'fiber' => 2.1, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 15, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Kale', 'category' => 'Vegetables', 'calories' => 49, 'protein' => 4.3, 'carbs' => 8.8, 'fat' => 0.9, 'fiber' => 3.6, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 15, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => false, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Celery', 'category' => 'Vegetables', 'calories' => 16, 'protein' => 0.7, 'carbs' => 3, 'fat' => 0.2, 'fiber' => 1.6, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 15, 'allergens' => [], 'is_low_sodium' => false, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Radish', 'category' => 'Vegetables', 'calories' => 16, 'protein' => 0.7, 'carbs' => 3.4, 'fat' => 0.1, 'fiber' => 1.6, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => false, 'glycemic_index' => 15, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => false, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Onion', 'category' => 'Vegetables', 'calories' => 40, 'protein' => 1.1, 'carbs' => 9.3, 'fat' => 0.1, 'fiber' => 1.7, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => false, 'glycemic_index' => 15, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Garlic', 'category' => 'Vegetables', 'calories' => 149, 'protein' => 6.4, 'carbs' => 33, 'fat' => 0.5, 'fiber' => 2.1, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => false, 'glycemic_index' => 30, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            
            // Additional Nuts & Seeds
            ['name' => 'Cashews', 'category' => 'Nuts', 'calories' => 553, 'protein' => 18.2, 'carbs' => 30.2, 'fat' => 43.8, 'fiber' => 3.3, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 22, 'allergens' => ['nuts'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Pistachios', 'category' => 'Nuts', 'calories' => 562, 'protein' => 20.2, 'carbs' => 27.2, 'fat' => 45.3, 'fiber' => 10.6, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 15, 'allergens' => ['nuts'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Sunflower Seeds', 'category' => 'Seeds', 'calories' => 584, 'protein' => 20.8, 'carbs' => 20, 'fat' => 51.5, 'fiber' => 8.6, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 20, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Pumpkin Seeds', 'category' => 'Seeds', 'calories' => 559, 'protein' => 30.2, 'carbs' => 10.7, 'fat' => 49.1, 'fiber' => 6, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 25, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Pecans', 'category' => 'Nuts', 'calories' => 691, 'protein' => 9.2, 'carbs' => 13.9, 'fat' => 72, 'fiber' => 9.6, 'serving_size' => 100, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 10, 'allergens' => ['nuts'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            
            // Additional Oils & Fats
            ['name' => 'Avocado Oil', 'category' => 'Oils', 'calories' => 884, 'protein' => 0, 'carbs' => 0, 'fat' => 100, 'fiber' => 0, 'serving_size' => 15, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 0, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Butter', 'category' => 'Dairy', 'calories' => 717, 'protein' => 0.8, 'carbs' => 0.1, 'fat' => 81.1, 'fiber' => 0, 'serving_size' => 15, 'is_veg' => true, 'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 0, 'allergens' => ['dairy'], 'is_low_sodium' => false, 'is_thyroid_friendly' => true, 'is_heart_friendly' => false, 'is_pcod_friendly' => false],
            
            // Additional Beverages & Alternatives
            ['name' => 'Soy Milk (Unsweetened)', 'category' => 'Beverages', 'calories' => 33, 'protein' => 3.3, 'carbs' => 1.8, 'fat' => 1.6, 'fiber' => 0.6, 'serving_size' => 240, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 34, 'allergens' => ['soy'], 'is_low_sodium' => true, 'is_thyroid_friendly' => false, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Almond Milk (Unsweetened)', 'category' => 'Beverages', 'calories' => 15, 'protein' => 0.5, 'carbs' => 0.3, 'fat' => 1.2, 'fiber' => 0.2, 'serving_size' => 240, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 25, 'allergens' => ['nuts'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Oat Milk', 'category' => 'Beverages', 'calories' => 42, 'protein' => 1, 'carbs' => 7, 'fat' => 1.5, 'fiber' => 0.8, 'serving_size' => 240, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 60, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Black Coffee', 'category' => 'Beverages', 'calories' => 1, 'protein' => 0.1, 'carbs' => 0, 'fat' => 0, 'fiber' => 0, 'serving_size' => 240, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 0, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Kombucha', 'category' => 'Beverages', 'calories' => 12, 'protein' => 0, 'carbs' => 3, 'fat' => 0, 'fiber' => 0, 'serving_size' => 240, 'is_veg' => true, 'is_vegan' => true, 'is_jain' => true, 'glycemic_index' => 50, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
        ];

        foreach ($foods as $food) {
            Food::firstOrCreate(['name' => $food['name']], $food);
        }

        $this->command->info('✅ Food database seeded with ' . count($foods) . ' items.');
    }
}
