<?php

namespace Database\Seeders;

use App\Models\Food;
use Illuminate\Database\Seeder;

class FoodSeeder extends Seeder
{
    public function run(): void
    {
        // Clean out legacy Western foods to maintain a strictly authentic Indian food database
        Food::whereIn('name', [
            'Salmon', 'Tuna', 'Cod', 'Sardines', 'Beef Steak', 'Pork Chops', 'Turkey Breast', 'Duck Meat',
            'Blueberries', 'Raspberries', 'Kale', 'Pecans', 'Kombucha', 'Quinoa', 'Whole Wheat Pasta', 'Cornmeal',
            'Black Beans', 'Edamame', 'Tempeh', 'Seitan', 'Cheddar Cheese', 'Mozzarella', 'Cottage Cheese', 'Zucchini', 'Celery', 'Asparagus',
            'Pineapple', 'Grapefruit', 'Kiwi', 'Peach', 'Plum', 'Pear', 'Grapes', 'Cherries', 'Broccoli', 'Sweet Potato', 'Mushroom',
            'Avocado Oil', 'Soy Milk (Unsweetened)', 'Almond Milk (Unsweetened)', 'Oat Milk', 'Black Coffee', 'Greek Yogurt', 'White Rice'
        ])->whereNull('user_id')->delete();

        $foods = [
            // ==========================================
            // 1. GRAINS & INDIAN BREADS / CEREALS
            // ==========================================
            ['name' => 'Roti (Chapati)',             'category' => 'Grains',    'calories' => 120, 'protein' => 3.8, 'carbs' => 22, 'fat' => 1.5, 'fiber' => 3.5, 'serving_size' => 40, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 52, 'allergens' => ['gluten'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Phulka',                     'category' => 'Grains',    'calories' => 85,  'protein' => 3.0, 'carbs' => 16, 'fat' => 0.5, 'fiber' => 2.8, 'serving_size' => 30, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 50, 'allergens' => ['gluten'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Multigrain Roti',            'category' => 'Grains',    'calories' => 110, 'protein' => 4.5, 'carbs' => 19, 'fat' => 1.8, 'fiber' => 4.2, 'serving_size' => 40, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 45, 'allergens' => ['gluten'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Bajra Roti (Pearl Millet)',  'category' => 'Grains',    'calories' => 115, 'protein' => 3.5, 'carbs' => 21, 'fat' => 1.6, 'fiber' => 3.8, 'serving_size' => 45, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 48, 'allergens' => [],         'is_low_sodium' => true, 'is_thyroid_friendly' => false, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Jowar Roti (Sorghum)',       'category' => 'Grains',    'calories' => 105, 'protein' => 3.2, 'carbs' => 22, 'fat' => 0.9, 'fiber' => 3.6, 'serving_size' => 45, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 50, 'allergens' => [],         'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Ragi Roti (Finger Millet)',   'category' => 'Grains',    'calories' => 110, 'protein' => 2.5, 'carbs' => 23, 'fat' => 0.6, 'fiber' => 4.5, 'serving_size' => 45, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 55, 'allergens' => [],         'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Poha (Flattened Rice)',      'category' => 'Grains',    'calories' => 180, 'protein' => 3.5, 'carbs' => 35, 'fat' => 3.0, 'fiber' => 2.0, 'serving_size' => 120, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 58, 'allergens' => [],         'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Upma (Semolina/Rava)',       'category' => 'Grains',    'calories' => 195, 'protein' => 4.5, 'carbs' => 32, 'fat' => 5.5, 'fiber' => 2.5, 'serving_size' => 140, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 60, 'allergens' => ['gluten'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => false],
            ['name' => 'Idli (Steamed)',             'category' => 'Grains',    'calories' => 65,  'protein' => 2.2, 'carbs' => 13, 'fat' => 0.3, 'fiber' => 1.2, 'serving_size' => 50, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 55, 'allergens' => [],         'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Plain Dosa',                 'category' => 'Grains',    'calories' => 135, 'protein' => 3.2, 'carbs' => 24, 'fat' => 3.0, 'fiber' => 1.4, 'serving_size' => 70, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 62, 'allergens' => [],         'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => false],
            ['name' => 'Moong Dal Chilla',           'category' => 'Grains',    'calories' => 140, 'protein' => 8.5, 'carbs' => 18, 'fat' => 3.5, 'fiber' => 4.0, 'serving_size' => 90, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 38, 'allergens' => [],         'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Besan Chilla',               'category' => 'Grains',    'calories' => 150, 'protein' => 7.8, 'carbs' => 19, 'fat' => 4.2, 'fiber' => 3.8, 'serving_size' => 90, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 40, 'allergens' => [],         'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Vegetable Dalia (Broken Wheat)','category' => 'Grains', 'calories' => 160, 'protein' => 5.2, 'carbs' => 30, 'fat' => 2.2, 'fiber' => 4.8, 'serving_size' => 150, 'serving_unit' => 'g', 'is_veg' => true, 'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 46, 'allergens' => ['gluten'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Steamed Basmati Rice',       'category' => 'Grains',    'calories' => 160, 'protein' => 3.4, 'carbs' => 35, 'fat' => 0.5, 'fiber' => 0.8, 'serving_size' => 130, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 68, 'allergens' => [],         'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => false],
            ['name' => 'Brown Rice',                 'category' => 'Grains',    'calories' => 145, 'protein' => 3.8, 'carbs' => 30, 'fat' => 1.2, 'fiber' => 2.8, 'serving_size' => 130, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 50, 'allergens' => [],         'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Moong Dal Khichdi',          'category' => 'Grains',    'calories' => 190, 'protein' => 7.0, 'carbs' => 34, 'fat' => 3.2, 'fiber' => 3.5, 'serving_size' => 160, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 52, 'allergens' => [],         'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Masala Oats',                'category' => 'Grains',    'calories' => 170, 'protein' => 6.2, 'carbs' => 29, 'fat' => 3.5, 'fiber' => 4.5, 'serving_size' => 150, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 52, 'allergens' => [],         'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Oats',                       'category' => 'Grains',    'calories' => 195, 'protein' => 8.5, 'carbs' => 33, 'fat' => 3.5, 'fiber' => 5.3, 'serving_size' => 50, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 53, 'allergens' => [],         'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Whole Wheat Bread',          'category' => 'Grains',    'calories' => 140, 'protein' => 6.5, 'carbs' => 25, 'fat' => 1.8, 'fiber' => 3.6, 'serving_size' => 55, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => false, 'glycemic_index' => 53, 'allergens' => ['gluten'], 'is_low_sodium' => false, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Sattu Flour',                'category' => 'Grains',    'calories' => 165, 'protein' => 10.5,'carbs' => 26, 'fat' => 2.4, 'fiber' => 6.2, 'serving_size' => 45, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 35, 'allergens' => [],         'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],

            // ==========================================
            // 2. DALS, LEGUMES & PLANT PROTEIN (PULSES)
            // ==========================================
            ['name' => 'Yellow Moong Dal',           'category' => 'Legumes',   'calories' => 145, 'protein' => 9.2, 'carbs' => 22, 'fat' => 2.5, 'fiber' => 5.5, 'serving_size' => 150, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 32, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Toor Dal (Arhar Dal)',       'category' => 'Legumes',   'calories' => 155, 'protein' => 8.8, 'carbs' => 24, 'fat' => 2.8, 'fiber' => 5.2, 'serving_size' => 150, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 35, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Masoor Dal (Red Lentils)',   'category' => 'Legumes',   'calories' => 140, 'protein' => 9.5, 'carbs' => 21, 'fat' => 2.2, 'fiber' => 5.8, 'serving_size' => 150, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 30, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Chana Dal',                  'category' => 'Legumes',   'calories' => 160, 'protein' => 8.5, 'carbs' => 25, 'fat' => 3.0, 'fiber' => 6.5, 'serving_size' => 150, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 28, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Rajma (Kidney Beans)',       'category' => 'Legumes',   'calories' => 175, 'protein' => 10.2,'carbs' => 28, 'fat' => 2.5, 'fiber' => 7.2, 'serving_size' => 160, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => false, 'glycemic_index' => 29, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Chhole (Chickpeas Curry)',   'category' => 'Legumes',   'calories' => 195, 'protein' => 9.8, 'carbs' => 30, 'fat' => 4.5, 'fiber' => 7.5, 'serving_size' => 160, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => false, 'glycemic_index' => 33, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Kala Chana (Black Chickpeas)','category' => 'Legumes', 'calories' => 165, 'protein' => 10.5,'carbs' => 26, 'fat' => 2.8, 'fiber' => 8.5, 'serving_size' => 150, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => false, 'glycemic_index' => 28, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Sprouted Moong (Boiled)',    'category' => 'Legumes',   'calories' => 120, 'protein' => 9.5, 'carbs' => 19, 'fat' => 0.8, 'fiber' => 6.2, 'serving_size' => 140, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 25, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Soya Chunks Curry',          'category' => 'Legumes',   'calories' => 170, 'protein' => 19.5,'carbs' => 13, 'fat' => 3.8, 'fiber' => 5.2, 'serving_size' => 150, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => false, 'glycemic_index' => 20, 'allergens' => ['soy'], 'is_low_sodium' => true, 'is_thyroid_friendly' => false, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Sambhar (South Indian)',     'category' => 'Legumes',   'calories' => 110, 'protein' => 5.2, 'carbs' => 18, 'fat' => 2.0, 'fiber' => 4.5, 'serving_size' => 160, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 38, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],

            // ==========================================
            // 3. DAIRY & VEGETARIAN PROTEIN
            // ==========================================
            ['name' => 'Paneer (Raw / Grilled)',     'category' => 'Dairy',     'calories' => 265, 'protein' => 18.3,'carbs' => 3.2, 'fat' => 20.8,'fiber' => 0.0, 'serving_size' => 100, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => false, 'is_jain' => true,  'glycemic_index' => 25, 'allergens' => ['dairy'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => false, 'is_pcod_friendly' => true],
            ['name' => 'Paneer Bhurji',              'category' => 'Dairy',     'calories' => 220, 'protein' => 14.5,'carbs' => 4.8, 'fat' => 16.2,'fiber' => 1.2, 'serving_size' => 120, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 27, 'allergens' => ['dairy'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => false, 'is_pcod_friendly' => true],
            ['name' => 'Palak Paneer',               'category' => 'Dairy',     'calories' => 210, 'protein' => 12.8,'carbs' => 6.2, 'fat' => 15.0,'fiber' => 3.2, 'serving_size' => 150, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 26, 'allergens' => ['dairy'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => false, 'is_pcod_friendly' => true],
            ['name' => 'Curd (Dahi)',                'category' => 'Dairy',     'calories' => 98,  'protein' => 6.2, 'carbs' => 7.0, 'fat' => 5.2, 'fiber' => 0.0, 'serving_size' => 150, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => false, 'is_jain' => true,  'glycemic_index' => 28, 'allergens' => ['dairy'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Cucumber Raita',             'category' => 'Dairy',     'calories' => 75,  'protein' => 4.5, 'carbs' => 6.5, 'fat' => 3.5, 'fiber' => 0.8, 'serving_size' => 120, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => false, 'is_jain' => true,  'glycemic_index' => 25, 'allergens' => ['dairy'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Chaas (Spiced Buttermilk)',  'category' => 'Beverages', 'calories' => 40,  'protein' => 2.8, 'carbs' => 3.6, 'fat' => 1.5, 'fiber' => 0.2, 'serving_size' => 200, 'serving_unit' => 'ml','is_veg' => true,  'is_vegan' => false, 'is_jain' => true,  'glycemic_index' => 20, 'allergens' => ['dairy'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Cow Milk (Low Fat)',         'category' => 'Dairy',     'calories' => 95,  'protein' => 6.4, 'carbs' => 9.5, 'fat' => 3.0, 'fiber' => 0.0, 'serving_size' => 200, 'serving_unit' => 'ml','is_veg' => true,  'is_vegan' => false, 'is_jain' => true,  'glycemic_index' => 30, 'allergens' => ['dairy'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Tofu (Soya Paneer)',         'category' => 'Legumes',   'calories' => 85,  'protein' => 9.5, 'carbs' => 2.1, 'fat' => 4.5, 'fiber' => 1.2, 'serving_size' => 100, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 15, 'allergens' => ['soy'],   'is_low_sodium' => true, 'is_thyroid_friendly' => false, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Desi Ghee',                  'category' => 'Oils',      'calories' => 88,  'protein' => 0.0, 'carbs' => 0.0, 'fat' => 10.0,'fiber' => 0.0, 'serving_size' => 10,  'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => false, 'is_jain' => true,  'glycemic_index' => 0,  'allergens' => ['dairy'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => false, 'is_pcod_friendly' => false],

            // ==========================================
            // 4. NON-VEGETARIAN (INDIAN MAINSTAYS)
            // ==========================================
            ['name' => 'Boiled Eggs (2 Eggs)',       'category' => 'Poultry',   'calories' => 145, 'protein' => 12.6,'carbs' => 1.1, 'fat' => 9.8, 'fiber' => 0.0, 'serving_size' => 100, 'serving_unit' => 'g', 'is_veg' => false, 'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 0,  'allergens' => ['eggs'],  'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Egg Bhurji (Indian Scramble)','category' => 'Poultry',  'calories' => 175, 'protein' => 13.5,'carbs' => 3.5, 'fat' => 12.0,'fiber' => 0.8, 'serving_size' => 120, 'serving_unit' => 'g', 'is_veg' => false, 'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 0,  'allergens' => ['eggs'],  'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Homestyle Egg Curry (2 Eggs)','category' => 'Poultry',  'calories' => 210, 'protein' => 14.0,'carbs' => 6.5, 'fat' => 14.2,'fiber' => 1.5, 'serving_size' => 160, 'serving_unit' => 'g', 'is_veg' => false, 'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 10, 'allergens' => ['eggs'],  'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Chicken Tikka (Tandoori)',   'category' => 'Poultry',   'calories' => 195, 'protein' => 30.0,'carbs' => 3.2, 'fat' => 6.5, 'fiber' => 0.5, 'serving_size' => 130, 'serving_unit' => 'g', 'is_veg' => false, 'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 0,  'allergens' => ['dairy'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Homestyle Chicken Curry',    'category' => 'Poultry',   'calories' => 240, 'protein' => 28.5,'carbs' => 5.2, 'fat' => 11.5,'fiber' => 1.2, 'serving_size' => 170, 'serving_unit' => 'g', 'is_veg' => false, 'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 10, 'allergens' => [],        'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Grilled Chicken Breast',     'category' => 'Poultry',   'calories' => 165, 'protein' => 31.0,'carbs' => 0.0, 'fat' => 3.6, 'fiber' => 0.0, 'serving_size' => 100, 'serving_unit' => 'g', 'is_veg' => false, 'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 0,  'allergens' => [],        'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Rohu / Katla Fish Curry',    'category' => 'Seafood',   'calories' => 190, 'protein' => 22.5,'carbs' => 4.0, 'fat' => 9.2, 'fiber' => 0.8, 'serving_size' => 150, 'serving_unit' => 'g', 'is_veg' => false, 'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 5,  'allergens' => ['fish'],  'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Prawns Masala',              'category' => 'Seafood',   'calories' => 160, 'protein' => 22.0,'carbs' => 4.5, 'fat' => 6.0, 'fiber' => 0.9, 'serving_size' => 140, 'serving_unit' => 'g', 'is_veg' => false, 'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 5,  'allergens' => ['shellfish'],'is_low_sodium'=> true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Mutton Curry (Lean)',        'category' => 'Meat',      'calories' => 280, 'protein' => 24.0,'carbs' => 4.2, 'fat' => 18.5,'fiber' => 1.0, 'serving_size' => 150, 'serving_unit' => 'g', 'is_veg' => false, 'is_vegan' => false, 'is_jain' => false, 'glycemic_index' => 5,  'allergens' => [],        'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => false, 'is_pcod_friendly' => true],

            // ==========================================
            // 5. INDIAN VEGETABLES & SABZIS
            // ==========================================
            ['name' => 'Bhindi Masala (Okra)',       'category' => 'Vegetables','calories' => 85,  'protein' => 2.5, 'carbs' => 8.5, 'fat' => 4.8, 'fiber' => 3.8, 'serving_size' => 120, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => false, 'glycemic_index' => 20, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Palak Sabzi (Spinach)',      'category' => 'Vegetables','calories' => 65,  'protein' => 3.8, 'carbs' => 5.2, 'fat' => 3.5, 'fiber' => 3.5, 'serving_size' => 130, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => false, 'glycemic_index' => 15, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Methi Sabzi (Fenugreek)',    'category' => 'Vegetables','calories' => 70,  'protein' => 4.2, 'carbs' => 6.0, 'fat' => 3.2, 'fiber' => 4.2, 'serving_size' => 120, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => false, 'glycemic_index' => 15, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Lauki Sabzi (Bottle Gourd)', 'category' => 'Vegetables','calories' => 55,  'protein' => 1.8, 'carbs' => 6.5, 'fat' => 2.5, 'fiber' => 2.8, 'serving_size' => 140, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 15, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Tori Sabzi (Ridge Gourd)',   'category' => 'Vegetables','calories' => 50,  'protein' => 1.5, 'carbs' => 5.8, 'fat' => 2.2, 'fiber' => 2.5, 'serving_size' => 140, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 15, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Karela Sabzi (Bitter Gourd)','category' => 'Vegetables','calories' => 75,  'protein' => 2.8, 'carbs' => 7.2, 'fat' => 4.0, 'fiber' => 3.6, 'serving_size' => 110, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => false, 'glycemic_index' => 12, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Baingan Bharta (Eggplant)',  'category' => 'Vegetables','calories' => 95,  'protein' => 2.2, 'carbs' => 8.5, 'fat' => 5.8, 'fiber' => 4.2, 'serving_size' => 130, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => false, 'glycemic_index' => 15, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Gobhi Matar Sabzi',          'category' => 'Vegetables','calories' => 90,  'protein' => 3.8, 'carbs' => 11.2,'fat' => 3.5, 'fiber' => 4.0, 'serving_size' => 130, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => false, 'glycemic_index' => 25, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => false, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Patta Gobhi (Cabbage)',      'category' => 'Vegetables','calories' => 70,  'protein' => 2.0, 'carbs' => 7.8, 'fat' => 3.2, 'fiber' => 3.2, 'serving_size' => 120, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 15, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => false, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Shimla Mirch (Capsicum)',    'category' => 'Vegetables','calories' => 65,  'protein' => 1.8, 'carbs' => 6.2, 'fat' => 3.8, 'fiber' => 2.8, 'serving_size' => 110, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 15, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Gajar Matar (Carrot & Peas)','category' => 'Vegetables','calories' => 85,  'protein' => 2.8, 'carbs' => 12.0,'fat' => 2.8, 'fiber' => 3.6, 'serving_size' => 120, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => false, 'glycemic_index' => 35, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Cucumber (Kheera Salad)',    'category' => 'Vegetables','calories' => 15,  'protein' => 0.7, 'carbs' => 3.6, 'fat' => 0.1, 'fiber' => 1.2, 'serving_size' => 100, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 15, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Tomato (Tamatar)',           'category' => 'Vegetables','calories' => 18,  'protein' => 0.9, 'carbs' => 3.9, 'fat' => 0.2, 'fiber' => 1.4, 'serving_size' => 100, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 15, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Radish (Mooli Salad)',       'category' => 'Vegetables','calories' => 16,  'protein' => 0.7, 'carbs' => 3.4, 'fat' => 0.1, 'fiber' => 1.6, 'serving_size' => 100, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => false, 'glycemic_index' => 15, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => false, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Beetroot (Chukandar)',       'category' => 'Vegetables','calories' => 43,  'protein' => 1.6, 'carbs' => 9.6, 'fat' => 0.2, 'fiber' => 2.8, 'serving_size' => 100, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => false, 'glycemic_index' => 61, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],

            // ==========================================
            // 6. INDIAN SNACKS & HEALTHY CHAATS
            // ==========================================
            ['name' => 'Roasted Makhana (Fox Nuts)', 'category' => 'Snacks',    'calories' => 110, 'protein' => 3.2, 'carbs' => 22, 'fat' => 1.2, 'fiber' => 4.2, 'serving_size' => 30, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 50, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Roasted Chana (Bhuna Chana)','category' => 'Snacks',    'calories' => 135, 'protein' => 7.5, 'carbs' => 21, 'fat' => 2.2, 'fiber' => 5.5, 'serving_size' => 35, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 28, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Sprouts Chaat',              'category' => 'Snacks',    'calories' => 130, 'protein' => 8.2, 'carbs' => 21, 'fat' => 1.5, 'fiber' => 5.8, 'serving_size' => 120, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => false, 'glycemic_index' => 25, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Khaman Dhokla (Steamed)',    'category' => 'Snacks',    'calories' => 140, 'protein' => 5.2, 'carbs' => 22, 'fat' => 3.5, 'fiber' => 2.2, 'serving_size' => 80, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 45, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Roasted Peanuts (Moongfali)','category' => 'Nuts',      'calories' => 160, 'protein' => 7.2, 'carbs' => 4.5, 'fat' => 13.8,'fiber' => 2.5, 'serving_size' => 28, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 14, 'allergens' => ['nuts'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Whole Wheat Khakhra',        'category' => 'Snacks',    'calories' => 120, 'protein' => 3.5, 'carbs' => 22, 'fat' => 2.0, 'fiber' => 3.5, 'serving_size' => 30, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 50, 'allergens' => ['gluten'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Murmura (Puffed Rice Bhel)', 'category' => 'Snacks',    'calories' => 110, 'protein' => 2.2, 'carbs' => 24, 'fat' => 0.4, 'fiber' => 1.2, 'serving_size' => 30, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 70, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => false],

            // ==========================================
            // 7. INDIAN FRUITS
            // ==========================================
            ['name' => 'Papaya (Papeeta)',           'category' => 'Fruits',    'calories' => 43,  'protein' => 0.5, 'carbs' => 11, 'fat' => 0.3, 'fiber' => 1.7, 'serving_size' => 100, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 60, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Guava (Amrood)',             'category' => 'Fruits',    'calories' => 68,  'protein' => 2.6, 'carbs' => 14, 'fat' => 0.9, 'fiber' => 5.4, 'serving_size' => 100, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 30, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Pomegranate (Anar)',         'category' => 'Fruits',    'calories' => 83,  'protein' => 1.7, 'carbs' => 18, 'fat' => 1.2, 'fiber' => 4.0, 'serving_size' => 100, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 35, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Apple (Seb)',                'category' => 'Fruits',    'calories' => 52,  'protein' => 0.3, 'carbs' => 14, 'fat' => 0.2, 'fiber' => 2.4, 'serving_size' => 100, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 36, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Banana (Kela)',              'category' => 'Fruits',    'calories' => 89,  'protein' => 1.1, 'carbs' => 23, 'fat' => 0.3, 'fiber' => 2.6, 'serving_size' => 100, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 51, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Watermelon (Tarbooz)',       'category' => 'Fruits',    'calories' => 30,  'protein' => 0.6, 'carbs' => 7.6,'fat' => 0.2, 'fiber' => 0.4, 'serving_size' => 100, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 72, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => false],
            ['name' => 'Mosambi (Sweet Lime)',       'category' => 'Fruits',    'calories' => 43,  'protein' => 0.8, 'carbs' => 10.5,'fat' => 0.1,'fiber' => 1.8, 'serving_size' => 100, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 40, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Orange (Santra)',            'category' => 'Fruits',    'calories' => 47,  'protein' => 0.9, 'carbs' => 12, 'fat' => 0.1, 'fiber' => 2.4, 'serving_size' => 100, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 43, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Mango (Aam)',                'category' => 'Fruits',    'calories' => 60,  'protein' => 0.8, 'carbs' => 15, 'fat' => 0.4, 'fiber' => 1.6, 'serving_size' => 100, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 51, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => false],
            ['name' => 'Jamun (Blackberry)',         'category' => 'Fruits',    'calories' => 60,  'protein' => 0.7, 'carbs' => 14, 'fat' => 0.2, 'fiber' => 1.5, 'serving_size' => 100, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 25, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Amla (Indian Gooseberry)',   'category' => 'Fruits',    'calories' => 44,  'protein' => 0.9, 'carbs' => 10.2,'fat' => 0.6,'fiber' => 4.3, 'serving_size' => 100, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 15, 'allergens' => [], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],

            // ==========================================
            // 8. NUTS, SEEDS & DRY FRUITS
            // ==========================================
            ['name' => 'Almonds (Badam)',            'category' => 'Nuts',      'calories' => 145, 'protein' => 5.2, 'carbs' => 5.5, 'fat' => 12.5,'fiber' => 3.1, 'serving_size' => 25, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 0,  'allergens' => ['nuts'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Walnuts (Akhrot)',           'category' => 'Nuts',      'calories' => 130, 'protein' => 3.0, 'carbs' => 2.8, 'fat' => 13.0,'fiber' => 1.4, 'serving_size' => 20, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 15, 'allergens' => ['nuts'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Cashews (Kaju)',             'category' => 'Nuts',      'calories' => 138, 'protein' => 4.5, 'carbs' => 7.5, 'fat' => 11.0,'fiber' => 0.8, 'serving_size' => 25, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 22, 'allergens' => ['nuts'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Chia Seeds (Sabja/Chia)',    'category' => 'Seeds',     'calories' => 73,  'protein' => 2.5, 'carbs' => 6.3, 'fat' => 4.6, 'fiber' => 5.2, 'serving_size' => 15, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 1,  'allergens' => [],         'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Flax Seeds (Alsi)',          'category' => 'Seeds',     'calories' => 80,  'protein' => 2.7, 'carbs' => 4.3, 'fat' => 6.3, 'fiber' => 4.1, 'serving_size' => 15, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 35, 'allergens' => [],         'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Pumpkin Seeds',              'category' => 'Seeds',     'calories' => 84,  'protein' => 4.5, 'carbs' => 1.6, 'fat' => 7.4, 'fiber' => 0.9, 'serving_size' => 15, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 25, 'allergens' => [],         'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Kishmish (Raisins)',         'category' => 'Nuts',      'calories' => 60,  'protein' => 0.6, 'carbs' => 15.8,'fat' => 0.1, 'fiber' => 0.8, 'serving_size' => 20, 'serving_unit' => 'g', 'is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 64, 'allergens' => [],         'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => false],

            // ==========================================
            // 9. INDIAN BEVERAGES & HEALTH COOLERS
            // ==========================================
            ['name' => 'Masala Chai (Low Sugar)',    'category' => 'Beverages', 'calories' => 45,  'protein' => 1.8, 'carbs' => 5.2, 'fat' => 1.8, 'fiber' => 0.0, 'serving_size' => 150, 'serving_unit' => 'ml','is_veg' => true,  'is_vegan' => false, 'is_jain' => true,  'glycemic_index' => 35, 'allergens' => ['dairy'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Tulsi Green Tea',            'category' => 'Beverages', 'calories' => 2,   'protein' => 0.0, 'carbs' => 0.2, 'fat' => 0.0, 'fiber' => 0.0, 'serving_size' => 200, 'serving_unit' => 'ml','is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 0,  'allergens' => [],        'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Coconut Water (Nariyal Pani)','category' => 'Beverages','calories' => 45, 'protein' => 1.7, 'carbs' => 8.9, 'fat' => 0.5, 'fiber' => 2.6, 'serving_size' => 240, 'serving_unit' => 'ml','is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 54, 'allergens' => [],        'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Namkeen Sattu Drink',        'category' => 'Beverages', 'calories' => 120, 'protein' => 7.2, 'carbs' => 18, 'fat' => 2.0, 'fiber' => 4.5, 'serving_size' => 250, 'serving_unit' => 'ml','is_veg' => true,  'is_vegan' => true,  'is_jain' => false, 'glycemic_index' => 30, 'allergens' => [],        'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Lemon Water (Nimbu Pani)',   'category' => 'Beverages', 'calories' => 15,  'protein' => 0.4, 'carbs' => 3.5, 'fat' => 0.0, 'fiber' => 0.4, 'serving_size' => 250, 'serving_unit' => 'ml','is_veg' => true,  'is_vegan' => true,  'is_jain' => true,  'glycemic_index' => 20, 'allergens' => [],        'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
            ['name' => 'Haldi Doodh (Turmeric Milk)','category' => 'Beverages', 'calories' => 110, 'protein' => 6.2, 'carbs' => 9.2, 'fat' => 4.5, 'fiber' => 0.2, 'serving_size' => 200, 'serving_unit' => 'ml','is_veg' => true,  'is_vegan' => false, 'is_jain' => true,  'glycemic_index' => 30, 'allergens' => ['dairy'], 'is_low_sodium' => true, 'is_thyroid_friendly' => true, 'is_heart_friendly' => true, 'is_pcod_friendly' => true],
        ];

        foreach ($foods as $food) {
            Food::updateOrCreate(['name' => $food['name']], $food);
        }

        $this->command->info('✅ Indian Food database successfully seeded with ' . count($foods) . ' authentic Indian items.');
    }
}
